name: Build & Deploy Storybook
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build 🔧
        uses: actions/checkout@v4
        with:
         token: ${{ secrets.GH_TOKEN }}
      - run: |
          npm install --legacy-peer-deps
          npm run deploy-storybook -- --ci
